version = 0.1
[default.deploy.parameters]
stack_name = "qa-test-automation"
resolve_s3 = true
s3_prefix = "qa-test-automation"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
