AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    CodeStarConnectionSSMParameter:
        Type: String
        Default: /qa-tests-automation/codebuild/codestar-connection-arn
        Description: SSM Parameter name that stores the CodeStar Connection ARN

Resources:
    ReportsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub ${AWS::StackName}-qa-reports
            WebsiteConfiguration:
                IndexDocument: index.html
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false

    ReportsBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ReportsBucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal: '*'
                      Action: s3:GetObject
                      Resource: !Sub ${ReportsBucket.Arn}/*

    BuildNotificationsTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: Build Notifications
            TopicName: qa-tests-automation

    NotificationFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: index.handler
            Runtime: python3.9
            Environment:
                Variables:
                    SNS_TOPIC_ARN: !Ref BuildNotificationsTopic
                    BUCKET_URL: !Sub http://${ReportsBucket}.s3-website-${AWS::Region}.amazonaws.com
            Policies:
                - SNSPublishMessagePolicy:
                      TopicName: !GetAtt BuildNotificationsTopic.TopicName
            Events:
                CodeBuildStateChange:
                    Type: EventBridgeRule
                    Properties:
                        Pattern:
                            source:
                                - aws.codebuild
                            detail-type:
                                - CodeBuild Build State Change
                            detail:
                                build-status:
                                    - SUCCEEDED
                                    - FAILED
                                project-name:
                                    - !Ref BuildProject
            InlineCode: |
                import json
                import boto3
                import os

                def handler(event, context):
                    sns = boto3.client('sns')

                    detail = event['detail']
                    status = detail['build-status']
                    build_number = str(detail['additional-information']['build-number']).split('.')[0]

                    message = f"Test execution result: {status}\n\nYou can view the detailed report at the following link:\n{os.environ['BUCKET_URL']}/reports/{build_number}/qa-report.html"

                    sns.publish(
                        TopicArn=os.environ['SNS_TOPIC_ARN'],
                        Message=message,
                        Subject=f'QA Test Results - {status}'
                    )

                    return {'statusCode': 200}

    BuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: qa-tests-automation
            Source:
                Type: GITHUB
                Location: https://github.com/TheRialNiels/QA_Test
            Environment:
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/standard:6.0
                Type: LINUX_CONTAINER
                EnvironmentVariables:
                    - Name: REPORTS_BUCKET
                      Value: !Ref ReportsBucket
                    - Name: COMMAND
                      Value: test.example
            Artifacts:
                Type: NO_ARTIFACTS
            ServiceRole: !GetAtt CodeBuildRole.Arn

    CodeBuildRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: codebuild.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: CodeBuildPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - logs:*
                                - s3:PutObject
                                - s3:PutObjectAcl
                            Resource:
                                - '*'
                                - !Sub ${ReportsBucket.Arn}/*
                          - Effect: Allow
                            Action:
                                - codestar-connections:UseConnection
                                - codestar-connections:GetConnectionToken
                            Resource: !Sub '{{resolve:ssm:${CodeStarConnectionSSMParameter}:1}}'

Outputs:
    ReportsBucketURL:
        Description: Static website URL to access test reports
        Value: !Sub http://${ReportsBucket}.s3-website-${AWS::Region}.amazonaws.com
